### ISSUE TITLE
能否考虑加入一下功能

### ISSUE THREAD

**Issue by crazynet999** [Andyfoo/SubTitleSearcher#1]
1、抓取信息源时标明是哪个字幕组的来源；
2、加入subhu的源等多几个？

**Comment by Andyfoo** [comment]
subhd源已经加了，没发布，因为我在改版，界面换成web html结构，方便加参数和美化

**Comment by crazynet999** [comment]
最好有抓取哪个字幕组的来源，那样可以选择字幕组，有些字幕组垃圾得很
