### ISSUE TITLE
subhd不好使，经常下不下来字幕

### ISSUE THREAD

**Issue by crazynet999** [Andyfoo/SubTitleSearcher#2]
subhd不好使，经常下不下来字幕，提示下载失败

**Comment by Andyfoo** [comment]
> subhd不好使，经常下不下来字幕，提示下载失败

抽空我再完善下提示，subhd网站不太好感觉，限制太多

**Comment by crazynet999** [comment]
字幕库1.3.1能下载的，2.0.2有报错，无法下载的情况

**Comment by Andyfoo** [comment]
> 字幕库1.3.1能下载的，2.0.2有报错，无法下载的情况

是压缩文件的时候吧？我重新换了个方式，等完善了发布

**Comment by Andyfoo** [comment]
> subhd不好使，经常下不下来字幕，提示下载失败

已经修改，更新试试吧，谢谢！
